id: A3F3A1E01
title: 'The Seed of Faith: A Prayer to the Sublime Ones'
type: translation
pechas:
- I473BC623
- ID8889868
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:33:54.047659
  last_modified_at: 2023-01-04 12:33:54.047682
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I473BC623/9678: DEDA
  ID8889868/335D: DEDA
